"""
节点包初始化文件
导出所有节点类和映射
"""

from .base64 import NODE_CLASS_MAPPINGS as BASE64_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BASE64_DISPLAY
from .url_loader import NODE_CLASS_MAPPINGS as URL_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as URL_DISPLAY
from .video import NODE_CLASS_MAPPINGS as VIDEO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY
from .api import NODE_CLASS_MAPPINGS as API_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as API_DISPLAY

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(BASE64_MAPPINGS)
NODE_CLASS_MAPPINGS.update(URL_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_MAPPINGS)
NODE_CLASS_MAPPINGS.update(API_MAPPINGS)

# 合并所有显示名称映射
NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(BASE64_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(URL_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(API_DISPLAY)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
